"""Write papers (canonical) and topic membership into the MaRDI Wikibase.

Membership lives on the TOPIC item: ``topic --has part(s) (P265)--> paper``.
Paper items stay topic-agnostic — they carry no statement about belonging to a
topic, so the canonical paper entity is never polluted by this feature.
"""
from __future__ import annotations

from ..harvest.arxiv_oai import PaperRecord
from . import model as M


def to_wbi_time(date: str) -> str:
    return f"+{date}T00:00:00Z"


class KGClient:
    def __init__(self, mc):
        self.mc = mc

    def get_paper_qid(self, arxiv_id: str) -> str | None:
        """Return the QID of the canonical paper item for ``arxiv_id`` if it exists."""
        existing = self.mc.search_entity_by_value(M.P_ARXIV_ID, arxiv_id)
        return existing[0] if existing else None

    def paper_has_tldr(self, paper_qid: str) -> bool:
        """Return whether the paper item already has a TL;DR claim."""
        item = self.mc.item.get(entity_id=paper_qid)
        return bool(item.get_value(M.P_TLDR))

    def import_paper(
        self,
        record: PaperRecord,
        tldr: str | None = None,
        keywords: list[str] | None = None,
        generated_by: str | None = None,
    ) -> str:
        """Upsert the canonical paper item (idempotent by arXiv ID). Returns its QID.

        Writes only paper-intrinsic statements; nothing about topics. ``tldr`` is
        an optional AI summary; ``keywords`` an optional list of topical tags
        (one statement each); ``generated_by`` an optional QID of the LLM that
        produced the item (sets ``generated by`` P1642). All stored on the paper.
        """
        # NOTE: use BARE local MaRDI PIDs/QIDs. A "wdt:"/"wd:" prefix makes
        # mardiclient interpret the id as a *Wikidata* one and remote-map it,
        # which both picks the wrong property and 404s. Our model.py ids are local.
        existing_qid = self.get_paper_qid(record.arxiv_id)
        if existing_qid:
            item = self.mc.item.get(entity_id=existing_qid)
        else:
            item = self.mc.item.new()
            item.labels.set("en", record.title[:250])

        item.add_claim(M.P_INSTANCE_OF, value=M.Q_SCHOLARLY_ARTICLE)
        item.add_claim(M.P_PROFILE_TYPE, value=M.Q_PUBLICATION_PROFILE)
        item.add_claim(M.P_ARXIV_ID, value=record.arxiv_id)
        if record.doi:
            item.add_claim(M.P_DOI, value=record.doi)
        item.add_claim(M.P_TITLE, value=record.title)
        if record.published:
            item.add_claim(M.P_PUBLICATION_DATE, value=to_wbi_time(record.published))
        for cat in record.categories:
            item.add_claim(M.P_ARXIV_CLASSIFICATION, value=cat)
        for name in record.authors:
            item.add_claim(M.P_AUTHOR_NAME_STRING, value=name)
        if tldr:
            item.add_claim(M.P_TLDR, value=tldr)
        for kw in keywords or []:
            item.add_claim(M.P_KEYWORDS, value=kw)
        if generated_by:
            item.add_claim(M.P_GENERATED_BY, value=generated_by)  # bare local QID

        return item.write().id

    def link_topic(self, topic_qid: str, paper_qid: str) -> None:
        """Add the paper to the topic's ``has part(s)`` (P265) list, idempotently.

        Reads the topic's current membership first and only writes when the paper
        is not already listed, so re-runs never duplicate entries.
        """
        topic_item = self.mc.item.get(entity_id=topic_qid)
        current = topic_item.get_value(M.P_HAS_PART) or []
        if paper_qid in current:
            return
        topic_item.add_claim(M.P_HAS_PART, value=paper_qid)
        topic_item.write()

    def get_theme_sitelink(self, theme_qid: str) -> str | None:
        """Return the wiki page title the theme item is connected to (``mardi``
        sitelink), or None if the item has no connected page yet."""
        item = self.mc.item.get(entity_id=theme_qid)
        sitelink = item.sitelinks.get(M.SITE_ID)
        return sitelink.title if sitelink else None

    def set_theme_sitelink(self, theme_qid: str, page_title: str) -> None:
        """Connect the theme item to its wiki page via the ``mardi`` sitelink."""
        item = self.mc.item.get(entity_id=theme_qid)
        item.sitelinks.set(site=M.SITE_ID, title=page_title)
        item.write()


def make_kg_client(config) -> KGClient:
    from mardiclient import MardiClient

    mc = MardiClient(
        user=config.mediawiki_bot_user,
        password=config.mediawiki_bot_password,
        login_with_bot=True,
        mediawiki_api_url=config.mediawiki_api_url,
        sparql_endpoint_url=config.sparql_endpoint_url,
        wikibase_url=config.wikibase_url,
    )
    return KGClient(mc)
