"""Write papers (canonical) and topic membership into the MaRDI Wikibase.

Membership lives on the TOPIC item: ``topic --has part(s) (P265)--> paper``.
Paper items stay topic-agnostic — they carry no statement about belonging to a
topic, so the canonical paper entity is never polluted by this feature.
"""
from __future__ import annotations

import logging
import requests

from wikibaseintegrator.datatypes import Item as WBItem
from wikibaseintegrator.models import Qualifiers

from ..harvest.arxiv_oai import PaperRecord
from . import model as M
from .author_resolver import AuthorResolver

log = logging.getLogger(__name__)


def to_wbi_time(date: str) -> str:
    return f"+{date}T00:00:00Z"


class KGClient:
    def __init__(
        self,
        mc,
        author_resolver: AuthorResolver | None = None,
        api_url: str = "",
        bot_user: str = "",
        bot_password: str = "",
    ):
        self.mc = mc
        self.author_resolver = author_resolver
        self._api_url = api_url
        self._bot_user = bot_user
        self._bot_password = bot_password
        self._session: requests.Session | None = None

    def _get_session(self) -> requests.Session:
        if self._session is None:
            s = requests.Session()
            lt = s.get(
                self._api_url,
                params={"action": "query", "meta": "tokens", "type": "login", "format": "json"},
                timeout=30,
            ).json()["query"]["tokens"]["logintoken"]
            s.post(
                self._api_url,
                data={"action": "login", "lgname": self._bot_user, "lgpassword": self._bot_password,
                      "lgtoken": lt, "format": "json"},
                timeout=30,
            )
            self._session = s
        return self._session

    def _csrf(self) -> str:
        return self._get_session().get(
            self._api_url,
            params={"action": "query", "meta": "tokens", "format": "json"},
            timeout=30,
        ).json()["query"]["tokens"]["csrftoken"]

    def get_paper_qid(self, arxiv_id: str) -> str | None:
        """Return the QID of the canonical paper item for ``arxiv_id`` if it exists."""
        existing = self.mc.search_entity_by_value(M.P_ARXIV_ID, arxiv_id)
        return existing[0] if existing else None

    def paper_has_tldr(self, paper_qid: str) -> bool:
        """Return whether the paper item already has a TL;DR claim."""
        item = self.mc.item.get(entity_id=paper_qid)
        return bool(item.get_value(M.P_TLDR))

    def import_paper(
        self,
        record: PaperRecord,
        tldr: str | None = None,
        keywords: list[str] | None = None,
        generated_by: str | None = None,
    ) -> str:
        """Upsert the canonical paper item (idempotent by arXiv ID). Returns its QID.

        Writes only paper-intrinsic statements; nothing about topics. ``tldr`` is
        an optional AI summary; ``keywords`` an optional list of topical tags
        (one statement each); ``generated_by`` an optional QID of the LLM that
        produced the item (sets ``generated by`` P1642). All stored on the paper.
        """
        # NOTE: use BARE local MaRDI PIDs/QIDs. A "wdt:"/"wd:" prefix makes
        # mardiclient interpret the id as a *Wikidata* one and remote-map it,
        # which both picks the wrong property and 404s. Our model.py ids are local.
        existing_qid = self.get_paper_qid(record.arxiv_id)
        if existing_qid:
            item = self.mc.item.get(entity_id=existing_qid)
        else:
            item = self.mc.item.new()
            item.labels.set("en", record.title[:250])

        item.add_claim(M.P_INSTANCE_OF, value=M.Q_SCHOLARLY_ARTICLE)
        item.add_claim(M.P_PROFILE_TYPE, value=M.Q_PUBLICATION_PROFILE)
        item.add_claim(M.P_ARXIV_ID, value=record.arxiv_id)
        if record.doi:
            item.add_claim(M.P_DOI, value=record.doi)
        item.add_claim(M.P_TITLE, value=record.title)
        if record.published:
            item.add_claim(M.P_PUBLICATION_DATE, value=to_wbi_time(record.published))
        for cat in record.categories:
            item.add_claim(M.P_ARXIV_CLASSIFICATION, value=cat)
        for name in record.authors:
            item.add_claim(M.P_AUTHOR_NAME_STRING, value=name)
            author_qid = self.author_resolver.resolve(name) if self.author_resolver else None
            if author_qid:
                qual = Qualifiers()
                qual.add(WBItem(prop_nr=M.P_GENERATED_BY, value=M.Q_LLM_AUTHOR_RESOLVER))
                item.add_claim(M.P_AUTHOR, value=author_qid, qualifiers=qual)
        if tldr:
            item.add_claim(M.P_TLDR, value=tldr)
        for kw in keywords or []:
            item.add_claim(M.P_KEYWORDS, value=kw)
        if generated_by:
            item.add_claim(M.P_GENERATED_BY, value=generated_by)  # bare local QID

        return item.write().id

    def link_topic(self, topic_qid: str, paper_qid: str) -> None:
        """Add the paper to the topic's ``has part(s)`` (P265) list, idempotently.

        Reads the topic's current membership first and only writes when the paper
        is not already listed, so re-runs never duplicate entries.
        """
        topic_item = self.mc.item.get(entity_id=topic_qid)
        current = topic_item.get_value(M.P_HAS_PART) or []
        if paper_qid in current:
            return
        topic_item.add_claim(M.P_HAS_PART, value=paper_qid)
        topic_item.write()

    def enforce_theme_limit(self, topic_qid: str, max_papers: int) -> int:
        """Unlink the oldest papers from a theme when it exceeds *max_papers*.

        Fetches all P265 claims on the theme, resolves publication dates (P28)
        for each linked paper, sorts oldest-first, and removes via wbremoveclaims
        until the count is at or below the limit. Returns the number removed.
        """
        if max_papers <= 0 or not self._api_url:
            return 0
        s = self._get_session()
        resp = s.get(
            self._api_url,
            params={"action": "wbgetentities", "ids": topic_qid, "props": "claims", "format": "json"},
            timeout=30,
        )
        resp.raise_for_status()
        p265 = resp.json()["entities"][topic_qid].get("claims", {}).get(M.P_HAS_PART, [])
        if len(p265) <= max_papers:
            return 0

        # Map paper QID -> claim GUID
        paper_guids: dict[str, str] = {}
        for c in p265:
            qid = (c.get("mainsnak", {}).get("datavalue", {}).get("value") or {}).get("id")
            if qid:
                paper_guids[qid] = c["id"]

        # Batch-fetch publication dates
        paper_qids = list(paper_guids)
        dates: dict[str, str] = {}
        for i in range(0, len(paper_qids), 50):
            batch = paper_qids[i : i + 50]
            r = s.get(
                self._api_url,
                params={"action": "wbgetentities", "ids": "|".join(batch), "props": "claims", "format": "json"},
                timeout=60,
            )
            for pqid, entity in r.json()["entities"].items():
                p28 = entity.get("claims", {}).get(M.P_PUBLICATION_DATE, [])
                dates[pqid] = p28[0]["mainsnak"]["datavalue"]["value"]["time"] if p28 else ""

        # Oldest first
        to_remove = sorted(paper_qids, key=lambda q: dates.get(q, ""))[: len(paper_qids) - max_papers]
        guids = [paper_guids[q] for q in to_remove]
        r = s.post(
            self._api_url,
            data={"action": "wbremoveclaims", "claim": "|".join(guids),
                  "token": self._csrf(), "format": "json", "bot": "1"},
            timeout=60,
        )
        if r.json().get("success"):
            log.info(
                "Theme %s: unlinked %d oldest paper(s) to enforce limit of %d",
                topic_qid, len(guids), max_papers,
            )
            return len(guids)
        log.warning("Theme %s: wbremoveclaims failed: %s", topic_qid, r.json().get("error"))
        return 0

    def get_theme_sitelink(self, theme_qid: str) -> str | None:
        """Return the wiki page title the theme item is connected to (``mardi``
        sitelink), or None if the item has no connected page yet."""
        item = self.mc.item.get(entity_id=theme_qid)
        sitelink = item.sitelinks.get(M.SITE_ID)
        return sitelink.title if sitelink else None

    def set_theme_sitelink(self, theme_qid: str, page_title: str) -> None:
        """Connect the theme item to its wiki page via the ``mardi`` sitelink."""
        item = self.mc.item.get(entity_id=theme_qid)
        item.sitelinks.set(site=M.SITE_ID, title=page_title)
        item.write()


def make_kg_client(config) -> KGClient:
    from mardiclient import MardiClient

    mc = MardiClient(
        user=config.mediawiki_bot_user,
        password=config.mediawiki_bot_password,
        login_with_bot=True,
        mediawiki_api_url=config.mediawiki_api_url,
        sparql_endpoint_url=config.sparql_endpoint_url,
        wikibase_url=config.wikibase_url,
    )
    resolver = AuthorResolver(config.mediawiki_api_url)
    return KGClient(
        mc,
        author_resolver=resolver,
        api_url=config.mediawiki_api_url,
        bot_user=config.mediawiki_bot_user,
        bot_password=config.mediawiki_bot_password,
    )
