"""Resolved MaRDI Wikibase property/class IDs. Verified 2026-06-24."""
from __future__ import annotations

# Properties
P_INSTANCE_OF = "P31"
P_ARXIV_ID = "P21"
P_ARXIV_CLASSIFICATION = "P22"
P_AUTHOR = "P16"
P_AUTHOR_NAME_STRING = "P43"
P_PUBLICATION_DATE = "P28"
P_TITLE = "P159"
P_DOI = "P27"
P_MAIN_SUBJECT = "P30"
P_SUBCLASS_OF = "P36"
P_AFFILIATION = "P55"
P_HAS_PART = "P265"            # topic --has part(s)--> paper (membership lives on the topic)
P_PROFILE_TYPE = "P1460"       # MaRDI profile type
P_TLDR = "P1963"               # AI-generated TL;DR summary (string)
P_KEYWORDS = "P1964"           # AI-generated topical keywords/tags (string, one claim per keyword)
P_GENERATED_BY = "P1642"       # "generated by" → QID of the agent/workflow that produced the item
P_ORCID = "P20"                # ORCID iD (on person items)
P_OPENALEX_ID = "P388"         # OpenAlex ID (external identifier; formatter URL https://openalex.org/$1)
P_ZBMATH_ID = "P225"           # zbMATH Open document ID (external identifier; formatter URL https://zbmath.org/$1)
P_ZBMATH_DE_NUMBER = "P1451"   # zbMATH DE Number (numeric internal document_id)
P_ZBMATH_AUTHOR_ID = "P676"    # zbMATH Autorenkennung (author identifier)
P_CITES_WORK = "P223"          # cites work (paper → paper citation link)
P_STATED_IN = "P98"            # stated in (reference snak — source of a claim)
P_PUBLISHED_IN = "P200"        # published in (journal/proceedings item)
P_MSC_ID = "P226"              # Mathematics Subject Classification ID (MSC code, one per claim)
P_ZBMATH_KEYWORDS = "P1450"    # zbMATH keywords (string, one claim per keyword)
P_OA_STATUS = "P1987"          # open access status (item-valued)
P_CONCEPTS = "P1988"           # OpenAlex concept labels (string, one claim per concept)
P_LICENSE = "P163"             # copyright license URL (string)

# P1642 "generated by" values
Q_WORKFLOW = "Q7270033"          # Prefect Workflow Research Theme Updater

# P98 "stated in" values (used in reference blocks on claims)
Q_SEMANTIC_SCHOLAR = "Q56440"   # Semantic Scholar (source of citation links)

# P1987 open access status values
Q_OA_GOLD   = "Q7270077"  # gold open access
Q_OA_HYBRID = "Q7270078"  # hybrid open access
Q_OA_BRONZE = "Q7270079"  # bronze open access
Q_OA_GREEN  = "Q7270080"  # green open access
Q_OA_CLOSED = "Q7270081"  # closed access

# Map from OpenAlex oa_status strings to KG QIDs
OA_STATUS_MAP: dict[str, str] = {
    "gold":   Q_OA_GOLD,
    "hybrid": Q_OA_HYBRID,
    "bronze": Q_OA_BRONZE,
    "green":  Q_OA_GREEN,
    "closed": Q_OA_CLOSED,
}

# Classes
Q_SCHOLARLY_ARTICLE = "Q56887"
Q_SCIENTIFIC_JOURNAL = "Q56973"   # scientific journal (used to filter P200 journal lookups)
Q_PREPRINT = "Q159099"
Q_PUBLICATION_PROFILE = "Q5976449"   # P1460 value for a publication ("Paper" profile)

# Sitelink site-id connecting a Wikibase item to its rendered wiki page on the
# MaRDI portal (verified from an existing connected item's sitelinks).
SITE_ID = "mardi"


def qid_from_uri(uri: str) -> str:
    """Extract the trailing Q-id from an entity URI (or pass through a bare QID)."""
    return uri.rstrip("/").rsplit("/", 1)[-1]
