"""Resolved MaRDI Wikibase property/class IDs. Verified 2026-06-20."""
from __future__ import annotations

# Properties
P_INSTANCE_OF = "P31"
P_ARXIV_ID = "P21"
P_ARXIV_CLASSIFICATION = "P22"
P_AUTHOR = "P16"
P_AUTHOR_NAME_STRING = "P43"
P_PUBLICATION_DATE = "P28"
P_TITLE = "P159"
P_DOI = "P27"
P_MAIN_SUBJECT = "P30"
P_SUBCLASS_OF = "P36"
P_AFFILIATION = "P55"
P_HAS_PART = "P265"            # topic --has part(s)--> paper (membership lives on the topic)
P_PROFILE_TYPE = "P1460"       # MaRDI profile type
P_TLDR = "P1963"               # AI-generated TL;DR summary (string)
P_KEYWORDS = "P1964"           # AI-generated topical keywords/tags (string, one claim per keyword)
P_GENERATED_BY = "P1642"       # "generated by" → QID of the LLM that produced the item
P_ORCID = "P20"                # ORCID iD (on person items)

# Item used as the P1642 "generated by" qualifier on AI-resolved P16 author claims
Q_LLM_AUTHOR_RESOLVER = "Q6510238"

# Classes
Q_SCHOLARLY_ARTICLE = "Q56887"
Q_PREPRINT = "Q159099"
Q_PUBLICATION_PROFILE = "Q5976449"   # P1460 value for a publication ("Paper" profile)

# Sitelink site-id connecting a Wikibase item to its rendered wiki page on the
# MaRDI portal (verified from an existing connected item's sitelinks).
SITE_ID = "mardi"


def qid_from_uri(uri: str) -> str:
    """Extract the trailing Q-id from an entity URI (or pass through a bare QID)."""
    return uri.rstrip("/").rsplit("/", 1)[-1]
