"""Environment-variable-first configuration."""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Mapping


@dataclass(frozen=True)
class Config:
    arxiv_query: str
    arxiv_query_property: str
    since_days: int
    model: str
    state_path: str
    research_theme_qid: str
    model_qid: str
    harvest_limit: int
    anthropic_api_key: str
    mediawiki_api_url: str
    mediawiki_bot_user: str
    mediawiki_bot_password: str
    wikibase_url: str
    sparql_endpoint_url: str
    dry_run: bool


def _flag(value: str) -> bool:
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def load_config(env: Mapping[str, str] = os.environ) -> Config:
    return Config(
        arxiv_query=env.get("TOPIC_OVERVIEWS_ARXIV_QUERY", ""),
        arxiv_query_property=env.get("TOPIC_OVERVIEWS_ARXIV_QUERY_PROPERTY", "P1965"),
        since_days=int(env.get("TOPIC_OVERVIEWS_SINCE_DAYS", "10")),
        model=env.get("TOPIC_OVERVIEWS_MODEL", "claude-haiku-4-5"),
        state_path=env.get("TOPIC_OVERVIEWS_STATE_PATH", "state.json"),
        research_theme_qid=env.get("TOPIC_OVERVIEWS_RESEARCH_THEME_QID", "Q0"),
        model_qid=env.get("TOPIC_OVERVIEWS_MODEL_QID", ""),  # KG item of the LLM ("generated by" P1642)
        harvest_limit=int(env.get("TOPIC_OVERVIEWS_HARVEST_LIMIT", "0")),  # 0 = unlimited
        anthropic_api_key=env.get("ANTHROPIC_API_KEY", ""),
        mediawiki_api_url=env.get("MEDIAWIKI_API_URL", ""),
        mediawiki_bot_user=env.get("MEDIAWIKI_BOT_USER", ""),
        mediawiki_bot_password=env.get("MEDIAWIKI_BOT_PASSWORD", ""),
        wikibase_url=env.get("WIKIBASE_URL", ""),
        sparql_endpoint_url=env.get("SPARQL_ENDPOINT_URL", ""),
        dry_run=_flag(env.get("TOPIC_OVERVIEWS_DRY_RUN", "false")),
    )
